-- Chinook PostgreSQL schema (auto-generated from Chinook_Sqlite.sqlite)
-- by backend/scripts/chinook_to_pg.py — W1, role A
DROP TABLE IF EXISTS "artist" CASCADE;
CREATE TABLE "artist" (
  "artistid" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" VARCHAR(120)
);

DROP TABLE IF EXISTS "album" CASCADE;
CREATE TABLE "album" (
  "albumid" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "title" VARCHAR(160)  NOT NULL,
  "artistid" BIGINT  NOT NULL,
  FOREIGN KEY ("artistid") REFERENCES "artist"("artistid")
);

DROP TABLE IF EXISTS "employee" CASCADE;
CREATE TABLE "employee" (
  "employeeid" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "lastname" VARCHAR(20)  NOT NULL,
  "firstname" VARCHAR(20)  NOT NULL,
  "title" VARCHAR(30),
  "reportsto" BIGINT,
  "birthdate" TIMESTAMP,
  "hiredate" TIMESTAMP,
  "address" VARCHAR(70),
  "city" VARCHAR(40),
  "state" VARCHAR(40),
  "country" VARCHAR(40),
  "postalcode" VARCHAR(10),
  "phone" VARCHAR(24),
  "fax" VARCHAR(24),
  "email" VARCHAR(60),
  FOREIGN KEY ("reportsto") REFERENCES "employee"("employeeid")
);

DROP TABLE IF EXISTS "customer" CASCADE;
CREATE TABLE "customer" (
  "customerid" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "firstname" VARCHAR(40)  NOT NULL,
  "lastname" VARCHAR(20)  NOT NULL,
  "company" VARCHAR(80),
  "address" VARCHAR(70),
  "city" VARCHAR(40),
  "state" VARCHAR(40),
  "country" VARCHAR(40),
  "postalcode" VARCHAR(10),
  "phone" VARCHAR(24),
  "fax" VARCHAR(24),
  "email" VARCHAR(60)  NOT NULL,
  "supportrepid" BIGINT,
  FOREIGN KEY ("supportrepid") REFERENCES "employee"("employeeid")
);

DROP TABLE IF EXISTS "genre" CASCADE;
CREATE TABLE "genre" (
  "genreid" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" VARCHAR(120)
);

DROP TABLE IF EXISTS "invoice" CASCADE;
CREATE TABLE "invoice" (
  "invoiceid" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "customerid" BIGINT  NOT NULL,
  "invoicedate" TIMESTAMP  NOT NULL,
  "billingaddress" VARCHAR(70),
  "billingcity" VARCHAR(40),
  "billingstate" VARCHAR(40),
  "billingcountry" VARCHAR(40),
  "billingpostalcode" VARCHAR(10),
  "total" NUMERIC(10,2)  NOT NULL,
  FOREIGN KEY ("customerid") REFERENCES "customer"("customerid")
);

DROP TABLE IF EXISTS "mediatype" CASCADE;
CREATE TABLE "mediatype" (
  "mediatypeid" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" VARCHAR(120)
);

DROP TABLE IF EXISTS "track" CASCADE;
CREATE TABLE "track" (
  "trackid" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" VARCHAR(200)  NOT NULL,
  "albumid" BIGINT,
  "mediatypeid" BIGINT  NOT NULL,
  "genreid" BIGINT,
  "composer" VARCHAR(220),
  "milliseconds" BIGINT  NOT NULL,
  "bytes" BIGINT,
  "unitprice" NUMERIC(10,2)  NOT NULL,
  FOREIGN KEY ("mediatypeid") REFERENCES "mediatype"("mediatypeid"),
  FOREIGN KEY ("genreid") REFERENCES "genre"("genreid"),
  FOREIGN KEY ("albumid") REFERENCES "album"("albumid")
);

DROP TABLE IF EXISTS "invoiceline" CASCADE;
CREATE TABLE "invoiceline" (
  "invoicelineid" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "invoiceid" BIGINT  NOT NULL,
  "trackid" BIGINT  NOT NULL,
  "unitprice" NUMERIC(10,2)  NOT NULL,
  "quantity" BIGINT  NOT NULL,
  FOREIGN KEY ("trackid") REFERENCES "track"("trackid"),
  FOREIGN KEY ("invoiceid") REFERENCES "invoice"("invoiceid")
);

DROP TABLE IF EXISTS "playlist" CASCADE;
CREATE TABLE "playlist" (
  "playlistid" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" VARCHAR(120)
);

DROP TABLE IF EXISTS "playlisttrack" CASCADE;
CREATE TABLE "playlisttrack" (
  "playlistid" BIGINT  NOT NULL,
  "trackid" BIGINT  NOT NULL,
  FOREIGN KEY ("trackid") REFERENCES "track"("trackid"),
  FOREIGN KEY ("playlistid") REFERENCES "playlist"("playlistid"),
  PRIMARY KEY ("playlistid", "trackid")
);

-- project tables
CREATE EXTENSION IF NOT EXISTS vector;;
CREATE TABLE IF NOT EXISTS biz_term (
        id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        canonical_name  TEXT NOT NULL,
        aliases         TEXT[] NOT NULL DEFAULT '{}',
        term_type       TEXT NOT NULL DEFAULT 'entity',
        binding         TEXT NOT NULL,
        description     TEXT NOT NULL DEFAULT '',
        source          TEXT NOT NULL DEFAULT 'auto',
        embedding       VECTOR(1024),
        created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
        UNIQUE (canonical_name, binding)
    );;
CREATE INDEX IF NOT EXISTS biz_term_alias_gin ON biz_term USING GIN (aliases);;
