"""Convert Chinook SQLite -> PostgreSQL (business DB) + bootstrap project tables.

Usage:
    python scripts/chinook_to_pg.py [--sqlite PATH] [--drop]

- Reads the official Chinook_Sqlite.sqlite (11 tables)
- Emits PG DDL (types mapped, PK identity, FKs) to data/db_schema/chinook_pg.sql
- Loads data with parameterized batches (topological FK order, self-refs last)
- Creates project tables: biz_term (术语库 v1) and enables pgvector

Idempotent for schema objects; --drop recreates Chinook tables.
"""

from __future__ import annotations

import argparse
import re
import sqlite3
import sys
from pathlib import Path

import psycopg

BACKEND = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(BACKEND))

from app.core.config import get_settings  # noqa: E402

CHINOOK_TABLES = [
    "Employee", "Customer", "Genre", "MediaType", "Playlist", "Album", "Artist",
    "Track", "Invoice", "InvoiceLine", "PlaylistTrack",
]

TYPE_MAP = [
    (re.compile(r"^NVARCHAR\((\d+)\)$", re.I), r"VARCHAR(\1)"),
    (re.compile(r"^VARCHAR\((\d+)\)$", re.I), r"VARCHAR(\1)"),
    (re.compile(r"^INTEGER$", re.I), "BIGINT"),
    (re.compile(r"^NUMERIC\((\d+),(\d+)\)$", re.I), r"NUMERIC(\1,\2)"),
    (re.compile(r"^DATETIME$", re.I), "TIMESTAMP"),
]


def map_type(sqlite_type: str) -> str:
    for pattern, repl in TYPE_MAP:
        if pattern.match(sqlite_type.strip()):
            return pattern.sub(repl, sqlite_type.strip())
    raise ValueError(f"unmapped sqlite type: {sqlite_type!r}")


def lower(name: str) -> str:
    """PG-unquoted-friendly names (documented deviation from canonical Chinook)."""
    return name.lower()


def read_sqlite_schema(con: sqlite3.Connection) -> dict[str, dict]:
    """Return {table: {ddl, columns[(name,type,pk,notnull,fks)]}}."""
    out: dict[str, dict] = {}
    for (name,) in con.execute(
        "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'"
    ):
        if name not in CHINOOK_TABLES:
            continue
        ddl = con.execute(
            "SELECT sql FROM sqlite_master WHERE type='table' AND name=?", (name,)
        ).fetchone()[0]
        cols = [
            {"name": r[1], "type": r[2], "pk": bool(r[5]), "notnull": bool(r[3])}
            for r in con.execute(f'PRAGMA table_info("{name}")')
        ]
        fks = [
            {"from": r[3], "ref_table": r[2], "to": r[4]}
            for r in con.execute(f'PRAGMA foreign_key_list("{name}")')
        ]
        out[name] = {"ddl": ddl, "columns": cols, "fks": fks}
    return out


def pg_ddl(schema: dict[str, dict]) -> tuple[list[str], list[str]]:
    """Generate (ddl_statements, insert_order) — both topologically FK-ordered."""
    order: list[str] = []
    visited: set[str] = set()

    def visit(name: str, stack: set[str]) -> None:
        if name in visited or name in stack:
            return
        stack.add(name)
        for fk in schema[name]["fks"]:
            if fk["ref_table"] in schema:
                visit(fk["ref_table"], stack)
        stack.discard(name)
        visited.add(name)
        order.append(name)

    for t in schema:
        visit(t, set())

    stmts: list[str] = []
    for name in order:
        t = schema[name]
        col_defs = []
        pk_cols = [c["name"] for c in t["columns"] if c["pk"]]
        for c in t["columns"]:
            pgtype = map_type(c["type"])
            single_pk = c["pk"] and len(pk_cols) == 1
            identity = "GENERATED BY DEFAULT AS IDENTITY" if single_pk else ""
            pk = "PRIMARY KEY" if single_pk else ""
            nn = " NOT NULL" if c["notnull"] else ""
            col_defs.append(
                f'"{lower(c["name"])}" {pgtype} {" ".join(x for x in (identity, pk) if x)}{nn}'.strip()
            )
        fks = []
        for fk in t["fks"]:
            fks.append(
                f'FOREIGN KEY ("{lower(fk["from"])}") '
                f'REFERENCES "{lower(fk["ref_table"])}"("{lower(fk["to"])}")'
            )
        # composite PK (e.g. PlaylistTrack)
        if len(pk_cols) > 1:
            fks.append(f'PRIMARY KEY ({", ".join(f'"{lower(c)}"' for c in pk_cols)})')
        body = ",\n  ".join(col_defs + fks)
        stmts.append(
            f'DROP TABLE IF EXISTS "{lower(name)}" CASCADE;\n'
            f'CREATE TABLE "{lower(name)}" (\n  {body}\n);'
        )
    return stmts, [lower(n) for n in order]


PROJECT_DDL = [
    "CREATE EXTENSION IF NOT EXISTS vector;",
    """
    CREATE TABLE IF NOT EXISTS biz_term (
        id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        canonical_name  TEXT NOT NULL,
        aliases         TEXT[] NOT NULL DEFAULT '{}',
        term_type       TEXT NOT NULL DEFAULT 'entity',
        binding         TEXT NOT NULL,
        description     TEXT NOT NULL DEFAULT '',
        source          TEXT NOT NULL DEFAULT 'auto',
        embedding       VECTOR(1024),
        created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
        UNIQUE (canonical_name, binding)
    );
    """,
    "CREATE INDEX IF NOT EXISTS biz_term_alias_gin ON biz_term USING GIN (aliases);",
    # ---- business knowledge lives in the DB, not in prompts (架构原则 1：知识外置).
    # schema_meta.build_schema_context() reads these into the semi-static prompt layer.
    """COMMENT ON TABLE track IS '曲目表。业务规则：统计销量/排名时，同名曲目（不同专辑/版本）视为同一首，必须按 name 聚合，禁止按 trackid 分组。';""",
    """COMMENT ON TABLE invoiceline IS '订单明细表，销量(quantity)与销售额(unitprice*quantity)的事实来源。';""",
    """COMMENT ON TABLE invoice IS '发票表，total 为含税总额；客户维度分析优先关联 customer 表而非 billing 字段。';""",
]


def _default_sqlite() -> str:
    return str(_repo_root() / "data/db_raw/Chinook_Sqlite.sqlite")


def _repo_root() -> Path:
    """Host: repo/ (BACKEND.parent); container: data mounted at BACKEND/data."""
    if (BACKEND / "data").is_dir():
        return BACKEND
    return BACKEND.parent


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--sqlite", default=_default_sqlite())
    ap.add_argument("--drop", action="store_true", help="drop & recreate Chinook tables")
    ap.add_argument("--no-data", action="store_true")
    args = ap.parse_args()

    s = get_settings()
    lite = sqlite3.connect(args.sqlite)
    schema = read_sqlite_schema(lite)
    assert set(schema) == set(CHINOOK_TABLES), f"unexpected tables: {set(schema) ^ set(CHINOOK_TABLES)}"

    ddl, insert_order = pg_ddl(schema)
    out_dir = _repo_root() / "data/db_schema"
    out_dir.mkdir(parents=True, exist_ok=True)
    header = (
        "-- Chinook PostgreSQL schema (auto-generated from Chinook_Sqlite.sqlite)\n"
        "-- by backend/scripts/chinook_to_pg.py — W1, role A\n"
    )
    (out_dir / "chinook_pg.sql").write_text(
        header + "\n\n".join(
            stmt if stmt.startswith("DROP") else stmt for stmt in ddl
        ) + "\n\n-- project tables\n" + ";\n".join(x.strip() for x in PROJECT_DDL) + ";\n",
        encoding="utf-8",
    )

    with psycopg.connect(s.database_url, autocommit=True) as pg:
        for stmt in PROJECT_DDL:
            pg.execute(stmt)
        if args.drop:
            print("· dropping & creating Chinook tables …")
            for stmt in ddl:
                pg.execute(stmt)
        if not args.no_data:
            by_lower = {lower(k): {"columns": v["columns"], "orig": k} for k, v in schema.items()}
            for name in insert_order:
                info = by_lower[name]
                cols = [c["name"] for c in info["columns"]]
                rows = lite.execute(
                    f'SELECT {", ".join(f"[{c}]" for c in cols)} FROM "{info["orig"]}"'
                ).fetchall()
                placeholders = ", ".join(["%s"] * len(cols))
                lcols = ", ".join(lower(c) for c in cols)
                with pg.cursor() as cur, pg.transaction():
                    cur.executemany(
                        f'INSERT INTO "{name}" ({lcols})'
                        f" VALUES ({placeholders}) ON CONFLICT DO NOTHING",
                        rows,
                    )
                print(f"  {name:<15} {len(rows):>6} rows")

    # sanity
    with psycopg.connect(s.database_url, autocommit=True) as pg, pg.cursor() as cur:
        cur.execute("SELECT count(*) FROM track")
        track_count = cur.fetchone()[0]
        cur.execute("SELECT count(*) FROM invoiceline")
        il_count = cur.fetchone()[0]
    print(f"✓ Chinook imported: track={track_count}, invoiceline={il_count}")
    print(f"✓ DDL written to data/db_schema/chinook_pg.sql")


if __name__ == "__main__":
    main()
