"""KB chunk store: pgvector for dense + in-memory BM25 for sparse (W1 minimal).

W3 upgrade path (B): pgvector HNSW index + proper hybrid index at scale;
the retriever interface (search(query) -> [ChunkHit]) stays unchanged.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from typing import Sequence

import numpy as np

from ..core.config import get_settings
from ..db.session import get_conn
from ..ingestion.ir import ChunkIR, DocIR

_DOC_DDL = """
CREATE TABLE IF NOT EXISTS kb_doc (
    doc_id       TEXT PRIMARY KEY,
    name         TEXT NOT NULL,
    source_path  TEXT NOT NULL,
    pages        INT NOT NULL,
    parser       TEXT NOT NULL DEFAULT 'pymupdf',
    content_hash TEXT NOT NULL,
    meta         JSONB NOT NULL DEFAULT '{}',
    ingested_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
"""


def _chunk_ddl(dim: int) -> str:
    return f"""
CREATE TABLE IF NOT EXISTS kb_chunk (
    chunk_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_id      TEXT NOT NULL REFERENCES kb_doc ON DELETE CASCADE,
    page_start  INT NOT NULL,
    page_end    INT NOT NULL,
    breadcrumb  TEXT[] NOT NULL,
    text        TEXT NOT NULL,
    embedding   vector({dim})
);
CREATE INDEX IF NOT EXISTS kb_chunk_doc_idx ON kb_chunk (doc_id);
"""


@dataclass
class StoredChunk:
    chunk_id: int
    doc_id: str
    doc_name: str
    page_start: int
    page_end: int
    breadcrumb: list[str]
    text: str
    embedding: np.ndarray | None = None


def _parse_vector(val) -> np.ndarray | None:
    """pgvector returns text '[-0.03,...]' unless the psycopg adapter is registered."""
    if val is None:
        return None
    if isinstance(val, np.ndarray):
        return val.astype(np.float32)
    if isinstance(val, (list, tuple)):
        return np.asarray(val, dtype=np.float32)
    return np.array([float(x) for x in str(val).strip("[]()").split(",")],
                    dtype=np.float32)


class KBStore:
    def __init__(self, dim: int):
        self.dim = dim
        self._ensure_schema()

    def _ensure_schema(self) -> None:
        with get_conn(readonly=False) as conn, conn.cursor() as cur:
            cur.execute("CREATE EXTENSION IF NOT EXISTS vector;")
            cur.execute(_DOC_DDL)
            # explicit dim check: switching models (e.g. bge-small->BGE-M3) without
            # re-ingest produces cryptic insert errors — fail fast with guidance
            cur.execute(
                "SELECT format_type(a.atttypid, a.atttypmod) FROM pg_attribute a"
                " JOIN pg_class c ON c.oid = a.attrelid"
                " JOIN pg_namespace n ON n.oid = c.relnamespace"
                " WHERE n.nspname='public' AND c.relname='kb_chunk' AND a.attname='embedding'"
            )
            row = cur.fetchone()
            if row and f"vector({self.dim})" not in row[0]:
                raise RuntimeError(
                    f"kb_chunk.embedding is {row[0]} but current model dim={self.dim}. "
                    "Model changed? Drop and re-ingest: "
                    "psql -c 'DROP TABLE kb_chunk' && python scripts/ingest_docs.py --force"
                )
            cur.execute(_chunk_ddl(self.dim))

    # -- ingest -------------------------------------------------------------

    def upsert_doc(
        self,
        doc: DocIR,
        chunk_embeddings: np.ndarray,
    ) -> None:
        """Atomically replace a document, chunks and validated formulas."""
        assert len(doc.chunks) == len(chunk_embeddings), (
            f"{doc.doc_id}: {len(doc.chunks)} chunks vs "
            f"{len(chunk_embeddings)} embeddings"
        )

        formula_meta = doc.meta.get("formula_extraction")
        formula_replace_ready = (
            isinstance(formula_meta, dict)
            and bool(formula_meta.get("replace_ready"))
        )

        if formula_replace_ready:
            from ..formula import store as formula_store
            formula_store.ensure_schema()

        with get_conn(readonly=False) as conn, conn.cursor() as cur:
            with conn.transaction():
                cur.execute(
                    "DELETE FROM kb_doc WHERE doc_id = %s",
                    (doc.doc_id,),
                )
                cur.execute(
                    "INSERT INTO kb_doc "
                    "(doc_id, name, source_path, pages, parser, "
                    "content_hash, meta) "
                    "VALUES (%s,%s,%s,%s,%s,%s,%s)",
                    (
                        doc.doc_id,
                        doc.name,
                        doc.source_path,
                        doc.pages,
                        doc.parser,
                        doc.content_hash(),
                        json.dumps(
                            doc.meta,
                            ensure_ascii=False,
                        ),
                    ),
                )

                for chunk, embedding in zip(
                    doc.chunks,
                    chunk_embeddings,
                ):
                    cur.execute(
                        "INSERT INTO kb_chunk "
                        "(doc_id, page_start, page_end, "
                        "breadcrumb, text, embedding) "
                        "VALUES (%s,%s,%s,%s,%s,%s)",
                        (
                            doc.doc_id,
                            chunk.page_start,
                            chunk.page_end,
                            chunk.breadcrumb,
                            chunk.text,
                            embedding.tolist(),
                        ),
                    )

                if formula_replace_ready:
                    formula_store.replace_for_doc(
                        doc.doc_id,
                        doc.formulas,
                        cursor=cur,
                    )

    def update_assessment(self, doc: DocIR) -> bool:
        """Refresh metadata and validated formulas for unchanged content."""

        owned_keys = (
            "quality",
            "complexity",
            "complexity_details",
            "formula_extraction",
        )
        metadata = {
            key: doc.meta[key]
            for key in owned_keys
            if key in doc.meta
        }

        formula_meta = doc.meta.get("formula_extraction")
        formula_replace_ready = (
            isinstance(formula_meta, dict)
            and bool(formula_meta.get("replace_ready"))
        )

        if not metadata and not formula_replace_ready:
            return False

        if formula_replace_ready:
            from ..formula import store as formula_store
            formula_store.ensure_schema()

        with get_conn(readonly=False) as conn, conn.cursor() as cur:
            with conn.transaction():
                cur.execute(
                    "UPDATE kb_doc SET meta = meta || %s::jsonb"
                    " WHERE doc_id = %s AND content_hash = %s",
                    (
                        json.dumps(
                            metadata,
                            ensure_ascii=False,
                        ),
                        doc.doc_id,
                        doc.content_hash(),
                    ),
                )
                updated = cur.rowcount == 1

                if updated and formula_replace_ready:
                    formula_store.replace_for_doc(
                        doc.doc_id,
                        doc.formulas,
                        cursor=cur,
                    )

                return updated

    def doc_content_hash(self, doc_id: str) -> str | None:
        with get_conn() as conn, conn.cursor() as cur:
            cur.execute("SELECT content_hash FROM kb_doc WHERE doc_id = %s", (doc_id,))
            row = cur.fetchone()
            return row[0] if row else None

    # -- load ---------------------------------------------------------------

    def all_chunks(self) -> list[StoredChunk]:
        with get_conn() as conn, conn.cursor() as cur:
            cur.execute(
                "SELECT c.chunk_id, c.doc_id, d.name, c.page_start, c.page_end,"
                " c.breadcrumb, c.text, c.embedding"
                " FROM kb_chunk c JOIN kb_doc d ON d.doc_id = c.doc_id"
                " ORDER BY d.doc_id, c.chunk_id"
            )
            return [StoredChunk(
                chunk_id=r[0], doc_id=r[1], doc_name=r[2], page_start=r[3],
                page_end=r[4], breadcrumb=list(r[5]), text=r[6],
                embedding=_parse_vector(r[7]),
            ) for r in cur.fetchall()]
